# Generated by Django 6.0.4 on 2026-05-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='size',
            field=models.CharField(default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(2, 'Order Processed'), (3, 'Order Delivered'), (4, 'Order Rejected')], default=0),
        ),
    ]
