# Generated by Django 6.0.4 on 2026-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordereditem_size_alter_order_order_status'),
        ('product', '0005_alter_product_small_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cart'), (1, 'Order Confirmed'), (2, 'Order Processed'), (3, 'Order Delivered'), (4, 'Order Rejected')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ordereditem',
            unique_together={('owner', 'product', 'size')},
        ),
    ]
