# Generated by Django 6.0.4 on 2026-04-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_image1',
            field=models.ImageField(default='', upload_to='media/products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='small_image2',
            field=models.ImageField(default='', upload_to='media/products/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='small_image3',
            field=models.ImageField(default='', upload_to='media/products/'),
            preserve_default=False,
        ),
    ]
