# Generated by Django 6.0.4 on 2026-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_small_image1_product_small_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='small_image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
    ]
